name: release

on:
  push:
    branches:
      - main

jobs:
  changeset:
    name: Changeset
    if: ${{ github.repository_owner == 'hideoo' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm changeset tag
          commit: 'ci: release'
          title: 'ci: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        if: steps.changesets.outputs.published == 'true'
        run: pnpx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX Registry
        if: steps.changesets.outputs.published == 'true'
        run: pnpx ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
