name: release

on:
  push:
    branches:
      - main

jobs:
  changeset:
    name: Changeset
    if: ${{ github.repository_owner == 'hideoo' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Install Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: pnpm run version
          publish: pnpm changeset tag
          commit: 'ci: release'
          title: 'ci: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        if: steps.changesets.outputs.published == 'true'
        run: pnpx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX Registry
        if: steps.changesets.outputs.published == 'true'
        run: pnpx ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
